name: Auto RSS Update

on:
  schedule:
    - cron: '0 17 * * *' # 毎日日本時間 深夜2:00
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    # cloudscraper とその依存ライブラリをまとめてインストール
    - run: pip install beautifulsoup4 feedgen cloudscraper
    
    - run: python generate.py
    
    - uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        keep_files: false
